
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-16
owner: ucsb-cs156-f24
repo_name: team02-f24-16
pull_requests: [{"author":{"id":"U_kgDOB3D13A","is_bot":false,"login":"rohanpreetam","name":""},"headRefName":"rp-MenuItemReview-backend","number":72,"title":"Copied files for backend CRUD API","url":"https://github.com/ucsb-cs156-f24/team02-f24-16/pull/72"}]
