
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-16
owner: ucsb-cs156-f24
repo_name: team02-f24-16
pull_requests: [{"author":{"id":"MDQ6VXNlcjgyMzMyNjk2","is_bot":false,"login":"jayster7101","name":"Jayden"},"headRefName":"recReq-indexPage","number":88,"title":"Recommendation Request index page","url":"https://github.com/ucsb-cs156-f24/team02-f24-16/pull/88"},{"author":{"id":"U_kgDOB3Ckdw","is_bot":false,"login":"Salshriaan","name":""},"headRefName":"pr-85","number":87,"title":"Pr 85","url":"https://github.com/ucsb-cs156-f24/team02-f24-16/pull/87"},{"author":{"id":"U_kgDOB3Ckdw","is_bot":false,"login":"Salshriaan","name":""},"headRefName":"sa-Articles-backendPages","number":85,"title":"sa- fixed issues that conflict with main, this implements everything...","url":"https://github.com/ucsb-cs156-f24/team02-f24-16/pull/85"},{"author":{"id":"U_kgDOB3D13A","is_bot":false,"login":"rohanpreetam","name":""},"headRefName":"rp-MenuItemReview-backend","number":84,"title":"Form components completed","url":"https://github.com/ucsb-cs156-f24/team02-f24-16/pull/84"},{"author":{"id":"U_kgDOBtnpoQ","is_bot":false,"login":"li-kelly","name":""},"headRefName":"kl-udcmi-createpage","number":81,"title":"edited the create and index page files following examples and added the storyboard","url":"https://github.com/ucsb-cs156-f24/team02-f24-16/pull/81"},{"author":{"id":"MDQ6VXNlcjgyMzMyNjk2","is_bot":false,"login":"jayster7101","name":"Jayden"},"headRefName":"reqReq-pages-placeholder","number":76,"title":"recommendation request pages place holder","url":"https://github.com/ucsb-cs156-f24/team02-f24-16/pull/76"}]
