
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-16
owner: ucsb-cs156-f24
repo_name: team02-f24-16
pull_requests: [{"author":{"id":"U_kgDOBtJfBw","is_bot":false,"login":"cs11111111","name":""},"headRefName":"ClaireOrgInt","number":126,"title":"Added Integration Test for UCSBOrganization","url":"https://github.com/ucsb-cs156-f24/team02-f24-16/pull/126"},{"author":{"id":"U_kgDOBtnpoQ","is_bot":false,"login":"li-kelly","name":""},"headRefName":"kl-udcmi-test","number":124,"title":"Added the integration tests for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f24/team02-f24-16/pull/124"},{"author":{"id":"U_kgDOB3Ckdw","is_bot":false,"login":"Salshriaan","name":""},"headRefName":"sa-Articles-IntegrationTests","number":117,"title":"Sa articles integration tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-16/pull/117"}]
