
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-16
owner: ucsb-cs156-f24
repo_name: team02-f24-16
pull_requests: [{"author":{"id":"U_kgDOB3E0Rw","is_bot":false,"login":"ttnguyen908","name":"Tiffany Nguyen"},"headRefName":"Tiffany-HelpReq-Component","number":96,"title":"Tiffany-HelpReq-Component","url":"https://github.com/ucsb-cs156-f24/team02-f24-16/pull/96"},{"author":{"id":"MDQ6VXNlcjgyMzMyNjk2","is_bot":false,"login":"jayster7101","name":"Jayden"},"headRefName":"reqReq-pages-placeholder","number":76,"title":"recommendation request pages place holder","url":"https://github.com/ucsb-cs156-f24/team02-f24-16/pull/76"}]
