
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-16
owner: ucsb-cs156-f24
repo_name: team02-f24-16
pull_requests: [{"author":{"id":"MDQ6VXNlcjgyMzMyNjk2","is_bot":false,"login":"jayster7101","name":"Jayden"},"headRefName":"recReq-table","number":71,"title":"Recommendation Request react table and tests.","url":"https://github.com/ucsb-cs156-f24/team02-f24-16/pull/71"},{"author":{"id":"U_kgDOBtnpoQ","is_bot":false,"login":"li-kelly","name":""},"headRefName":"kl-form","number":70,"title":"form, story, test for ucsbdiningcommonsmenuitem","url":"https://github.com/ucsb-cs156-f24/team02-f24-16/pull/70"}]
