
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-16
owner: ucsb-cs156-f24
repo_name: team02-f24-16
pull_requests: [{"author":{"id":"MDQ6VXNlcjgyMzMyNjk2","is_bot":false,"login":"jayster7101","name":"Jayden"},"headRefName":"team3Main-int","number":110,"title":"Integration testing for a single method on the Recommendation Request data table","url":"https://github.com/ucsb-cs156-f24/team02-f24-16/pull/110"},{"author":{"id":"U_kgDOB3D13A","is_bot":false,"login":"rohanpreetam","name":""},"headRefName":"rp-MenuItemReview-indexpg","number":109,"title":"Index page added","url":"https://github.com/ucsb-cs156-f24/team02-f24-16/pull/109"},{"author":{"id":"U_kgDOB3E0Rw","is_bot":false,"login":"ttnguyen908","name":"Tiffany Nguyen"},"headRefName":"Tiffany-HelpRequest-PlaceholderPages","number":108,"title":"HelpRequest placeholder pages implemented!","url":"https://github.com/ucsb-cs156-f24/team02-f24-16/pull/108"},{"author":{"id":"U_kgDOB3E0Rw","is_bot":false,"login":"ttnguyen908","name":"Tiffany Nguyen"},"headRefName":"ttnguyen908-patch-2","number":107,"title":"Update App.js with HelpRequest Pages!","url":"https://github.com/ucsb-cs156-f24/team02-f24-16/pull/107"}]
